// import { config } from "@fortawesome/fontawesome-svg-core";
// import "../node_modules/@fortawesome/fontawesome-svg-core/styles.css";
// config.autoAddCss = false;
// import { Loading } from "@/loading";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

import Footer from "./components/Footer";
import CartContextProvider from "./context/CartContextProvider";
import UserContextProvider from "./context/UserContextProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Suspense fallback={<Loading />}> */}
        <UserContextProvider>
          <CartContextProvider>
            <Navbar />
            <main className="h-full max-h-full">{children}</main>
            {/* <Accordian /> */}
            <Footer />
          </CartContextProvider>
        </UserContextProvider>
        {/* </Suspense> */}
      </body>
    </html>
  );
}
