// import { config } from "@fortawesome/fontawesome-svg-core";
// import "../node_modules/@fortawesome/fontawesome-svg-core/styles.css";
// config.autoAddCss = false;

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

import Footer from "./components/Footer";
import CartProvider from "./context/CartProvider";
import UserProvider from "./context/UserProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <CartProvider>
            <Navbar />
            <main className="h-full max-h-full">{children}</main>
            {/* <Accordian /> */}
            <Footer />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
